// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCf8imFj7Bx6H9d5okvVQkgCKUbT5m5CBg',
    appId: '1:821342385580:web:955ef93a47a4ea34223609',
    messagingSenderId: '821342385580',
    projectId: 'haca-olx-clone',
    authDomain: 'haca-olx-clone.firebaseapp.com',
    storageBucket: 'haca-olx-clone.firebasestorage.app',
    measurementId: 'G-533SQ9SPTP',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyALVIkZmDdrlZrimxaG8thwl9QKzO3olQQ',
    appId: '1:821342385580:android:0391df3d93d2384c223609',
    messagingSenderId: '821342385580',
    projectId: 'haca-olx-clone',
    storageBucket: 'haca-olx-clone.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBjHSfy7XjEFeygTylX3Epk0EdNsQQUGFA',
    appId: '1:821342385580:ios:90a4017a98b735e5223609',
    messagingSenderId: '821342385580',
    projectId: 'haca-olx-clone',
    storageBucket: 'haca-olx-clone.firebasestorage.app',
    iosBundleId: 'com.example.olx',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBjHSfy7XjEFeygTylX3Epk0EdNsQQUGFA',
    appId: '1:821342385580:ios:90a4017a98b735e5223609',
    messagingSenderId: '821342385580',
    projectId: 'haca-olx-clone',
    storageBucket: 'haca-olx-clone.firebasestorage.app',
    iosBundleId: 'com.example.olx',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCf8imFj7Bx6H9d5okvVQkgCKUbT5m5CBg',
    appId: '1:821342385580:web:aa3ef086b4ce6832223609',
    messagingSenderId: '821342385580',
    projectId: 'haca-olx-clone',
    authDomain: 'haca-olx-clone.firebaseapp.com',
    storageBucket: 'haca-olx-clone.firebasestorage.app',
    measurementId: 'G-W76XMF2V1Z',
  );
}
